# Generated by Django 4.2.7 on 2026-02-11 01:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_object_key', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(default='tourism-prod-media', max_length=50)),
                ('mime_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING_AI', 'Pending Ai'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_AI', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='tourism.category')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tourism.city')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_AI', 'Pending Ai'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_AI', max_length=20)),
                ('text_ai_status', models.CharField(choices=[('PENDING_AI', 'Pending Ai'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_AI', max_length=20)),
                ('media_ai_status', models.CharField(blank=True, choices=[('PENDING_AI', 'Pending Ai'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tourism.media')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tourism.post')),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tourism.place')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tourism.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='tourism.user')),
            ],
            options={
                'db_table': 'post_votes',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tourism.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tourism.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='place',
            field=models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism.place'),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tourism.user'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tourism.province'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tourism.user')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('MEDIA', 'Media'), ('POST', 'Post')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_media', models.ForeignKey(blank=True, db_column='reported_media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tourism.media')),
                ('reported_post', models.ForeignKey(blank=True, db_column='reported_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tourism.post')),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tourism.user')),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['reporter'], name='idx_reports_reporter'), models.Index(fields=['status'], name='idx_reports_status')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tourism.place')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tourism.user')),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['user'], name='idx_ratings_user'), models.Index(fields=['place'], name='idx_ratings_place')],
            },
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'place'), name='unique_user_place_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 5)), name='valid_rating_score'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['user'], name='idx_post_votes_user'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['post'], name='idx_post_votes_post'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['post', 'is_like'], name='idx_post_votes_post_like'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_vote'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='idx_posts_user'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['place', 'status'], name='idx_posts_place_status'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent'], name='idx_posts_parent'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='idx_posts_created_desc'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['media'], name='idx_posts_media'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['deleted_at'], name='idx_posts_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='idx_places_city'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='idx_places_category'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='idx_notifications_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='idx_notifications_read'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['user'], name='idx_media_user'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['place', 'status'], name='idx_media_place_status'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['deleted_at'], name='idx_media_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='idx_cities_province'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_city_per_province'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='idx_activity_logs_user'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type'], name='idx_activity_logs_action'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='idx_activity_logs_created'),
        ),
    ]
